### ISSUE TITLE
Sammenligning mellom elveg2osm og nvdb2osm

### ISSUE THREAD

**Issue by ghost** [NKAmapper/nvdb2osm#1]
Sammenlignet det jeg fikk fra nvdb med `python2 nvdb2osm.py -vn -k 1201 > 1201.osm` og den nyeste ELVEGfilen som ligger tilgjengelig og endte med denne tabellen.

| key                     | nvdb2osm | elveg2osm |
|-------------------------|----------|-----------|
| amenity                 | 0        | 3         |
| barrier                 | 0        | 213       |
| bicycle                 | 2232     | 0         |
| bridge                  | 375      | 327       |
| cycleway                | 108      | 60        |
| cycleway:left           | 14       | 0         |
| cycleway:right          | 21       | 0         |
| ferry                   | 0        | 2         |
| FIXME                   | 67       | 171       |
| foot                    | 3623     | 3524      |
| footway                 | 54       | 2         |
| highway                 | 43749    | 21431     |
| junction                | 956      | 0         |
| lanes                   | 838      | 401       |
| lanes:backward          | 107      | 0         |
| lanes:forward           | 107      | 0         |
| lanes:psv               | 0        | 31        |
| layer                   | 804      | 667       |
| maxheight               | 0        | 131       |
| maxspeed                | 0        | 2629      |
| maxspeed:backward       | 0        | 1         |
| maxspeed:forward        | 0        | 1         |
| motorcar                | 57       | 0         |
| motorcar:lanes          | 21       | 0         |
| motorcar:lanes:backward | 25       | 0         |
| motorcar:lanes:forward  | 38       | 0         |
| name                    | 0        | 19165     |
| note                    | 0        | 2         |
| nvdb:date               | 0        | 10079     |
| nvdb:id                 | 0        | 10079     |
| oneway                  | 4480     | 2073      |
| psv                     | 57       | 22        |
| psv:lanes               | 21       | 0         |
| psv:lanes:backward      | 25       | 0         |
| psv:lanes:forward       | 38       | 0         |
| ref                     | 7476     | 2684      |
| route                   | 3        | 0         |
| route                   | 0        | 2         |
| tunnel                  | 437      | 347       |
| turn:lanes              | 2        | 0         |

Ser ut som nvdb2osm ikke har noen fartsgrenser eller navn, og det er en del ulikeheter (uten at jeg har noe formening om hva som er å foretrekke)

**Comment by NKAmapper** [comment]
Interessant. Den viktigste forskjellen her er at nvdb2osm ikke (ennå) henter inn vegobjekter (fagdata) og knytter sammen med vegnettet. Bare informasjon som ligger i vegnettet selv brukes. Det betyr at fartsgrenser, vegnavn, bommer og makshøyde ikke kommer med (de er alle vegobjekter i NVDB). Jeg har tanker om å knytte inn slikt i en senere versjon men det krever en helt annen behandling i programmet (i praksis oppbygging av en graf i minnet for hele nettet).

Til gjengjeld genererer nvdb2osm f.eks. turn:lanes, kollektivfelt og sykkelfelt.


Ellers kan noen forskjeller i antall komme av at det kan være flere og kortere vegsegmenter.

**Comment by NKAmapper** [comment]
Ny versjon
