### ISSUE TITLE
Ingen god støtte for "-vegurl" med API-url fra vegkart.no

### ISSUE THREAD

**Issue by haabe** [NKAmapper/nvdb2osm#11]
Et kartutsnitt fra vegkart.no genererer API-kall mot `vegnett/veglenkesekvener/segmentert`, og har med seg kartutsnitt-parameter basert på størrelsen på nettleseren -- eksempel: `https://nvdbapiles-v3.atlas.vegvesen.no/vegnett/veglenkesekvenser/segmentert?kartutsnitt=239655.6%2C6678316.987%2C241348.937%2C6679675.625`

Å endre koordinatene for kartutsnittet til WGS84 fungerer dersom `srid=4326` -- eksempel: `https://nvdbapiles-v3.atlas.vegvesen.no/vegnett/veglenkesekvenser/segmentert?srid=4326&kartutsnitt=11.465859979493205,64.01792506981553,11.517636911427205,64.00000163044928`

Men dette fungerer ikke med nvdb2osm, verken med srid satt eller ei. Dersom den ikke blir satt (siden den skal settes automatisk), begynner den å laste data før den feiler med HTTP 422:
```
nvdb2osm v1.5.0

Server:         https://nvdbapiles-v3.atlas.vegvesen.no/
API:            v2023.2.26, 2024-03-12
Data catalogue: v2.36, 2024-03-22
Last DB update: 2024-04-05

Ouput filename: nvdb_vegnett.osm

Loading NVDB data...
Done processing 1547 road objects/segments
Removing duplicate segments... Removed 2 segments
Merging object type #103 Fartsdemper...
Retry 1: HTTP Error 422: Unprocessable Entity
Retry 2: HTTP Error 422: Unprocessable Entity
´´´

**Comment by NKAmapper** [comment]
Det stemmer at kartutsnitt ikke er støttet for vegnett. Legger ut ny versjon 1.6 der dette er fikset nå.
