### ISSUE TITLE
Konvertere flere key:tags for bomstasjoner

### ISSUE THREAD

**Issue by ghost** [NKAmapper/nvdb2osm#2]
- `TAKST_LITEN_BIL` = `fee:car=*`
- `TAKST_STOR_BIL` = `fee:hgv=*`
- `BOMPENGEANLEGG_ID` / `BOMSTASJONSTYPE` = `barrier=toll_booth`
- `NAVN_BOMPENGEANLEGG_(FRA_CS)` = `operator=*`
- `("BOMSTASJONSTYPE"="#13133 AutoPASS + automatisk")` = `type=AutoPASS`
- `NAVN_BOMSTASJON` = `name=*`
- Hvis stasjonen har `BOMPENGEANLEGG_ID` så burde den være ref istedet for hva enn som blir ref nå. Det ser ut som ref til veien

Bomstasjonene får også en `highway`-tag på seg

**Comment by NKAmapper** [comment]
Gode forslag. Utfordringen er at det er veldig mange [objekttyper](http://labs.vegdata.no/nvdb-datakatalog/), hver med sin tagging. Så inntil videre hjelper bare programmet med å hente ut rådata fra NVDB for slike vegobjekter. Kan se etter hvert om jeg kan legge inn tagging-støtte for de uttrekkene som blir mest brukt.

Den langsiktige løsningen er bygge om hele programmet slik at vegobjektene flettes sammen med vegnettet, og da vil alt få tagging. Men i løpet av 2019 kommer v3 av api'et, så venter nok på det først.

**Comment by NKAmapper** [comment]
Implementert her: [toll2osm](https://github.com/osmno/toll2osm)
